./atpg -tdfatpg -ndet 1 ../sample_circuits/c17.ckt > ../tdf_patterns/c17.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c432.ckt > ../tdf_patterns/c432.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c499.ckt > ../tdf_patterns/c499.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c880.ckt > ../tdf_patterns/c880.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c1355.ckt > ../tdf_patterns/c1355.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c2670.ckt > ../tdf_patterns/c2670.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c3540.ckt > ../tdf_patterns/c3540.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c6288.ckt > ../tdf_patterns/c6288.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c7552.ckt > ../tdf_patterns/c7552.pat