./atpg -tdfatpg -ndet 1 ../sample_circuits/c17.ckt > ../tdf_patterns/c17_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c432.ckt > ../tdf_patterns/c432_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c499.ckt > ../tdf_patterns/c499_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c880.ckt > ../tdf_patterns/c880_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c1355.ckt > ../tdf_patterns/c1355_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c2670.ckt > ../tdf_patterns/c2670_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c3540.ckt > ../tdf_patterns/c3540_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c6288.ckt > ../tdf_patterns/c6288_noc.pat
./atpg -tdfatpg -ndet 1 ../sample_circuits/c7552.ckt > ../tdf_patterns/c7552_noc.pat